export async function createFoodAndWater({ speaker, actor, token, character, item, args, scope, workflow }) {
    new Sequence()

        .wait(1000)

        .effect()
        .file("jb2a.magic_signs.circle.02.conjuration.intro.dark_yellow")
        .atLocation(token)
        .scaleToObject(2)
        .belowTokens()

        .effect()
        .file("jb2a.magic_signs.circle.02.conjuration.loop.dark_yellow")
        .atLocation(token)
        .scaleToObject(2)
        .belowTokens()
        .delay(3000)
        .duration(8600)
        .fadeOut(1000)

        .effect()
        .file("jb2a.particles.swirl.orange.01.01")
        .atLocation(token)
        .scaleToObject(2)
        .belowTokens()
        .delay(2750)
        .fadeIn(750)
        .fadeOut(500)
        .opacity(0.5)
        .duration(9500)
        .fadeOut(1000)
        .mirrorX()

        .effect()
        .file("jb2a.detect_magic.circle.yellow")
        .atLocation(token, { offset: { x: 0, y: -45 } })
        .scaleToObject(2)
        .playbackRate(1)
        .opacity(0.75)
        .mask()
        .fadeIn(500)
        .fadeOut(1000)
        .duration(12250)
        .delay(3000)

        .effect()
        .file("jb2a.portals.horizontal.ring_masked.yellow")
        .atLocation(token, { offset: { x: 0, y: -30 } })
        .scaleToObject(0.65)
        .playbackRate(1)
        .belowTokens()
        .fadeIn(500)
        .fadeOut(1000)
        .duration(12250)
        .delay(3000)
        .zIndex(1)

        .effect()
        .file("animated-spell-effects-cartoon.cantrips.mending.yellow")
        .atLocation(token, { offset: { x: 70, y: 22 } })
        .scaleToObject(0.8)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .delay(3750)
        .playbackRate(0.65)

        .effect()
        .file("modules/mba-premades/icons/misc/food1.webp")
        .atLocation(token, { offset: { x: 70, y: 22 } })
        .scaleToObject(0.45)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .duration(11000)
        .fadeIn(750)
        .fadeOut(750)
        .rotate(340)
        .delay(4000)
        .name(`${token.document.name} Create food and Water`)

        .effect()
        .file("animated-spell-effects-cartoon.cantrips.mending.yellow")
        .atLocation(token, { offset: { x: 45, y: -61 } })
        .scaleToObject(0.8)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .delay(4750)
        .playbackRate(0.65)

        .effect()
        .file("modules/mba-premades/icons/misc/food2.webp")
        .atLocation(token, { offset: { x: 45, y: -61 } })
        .scaleToObject(0.3)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .duration(10000)
        .fadeIn(750)
        .fadeOut(750)
        .rotate(20)
        .delay(5000)
        .name(`${token.document.name} Create food and Water`)

        .effect()
        .file("animated-spell-effects-cartoon.cantrips.mending.yellow")
        .atLocation(token, { offset: { x: -45, y: -61 } })
        .scaleToObject(0.8)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .delay(5750)
        .playbackRate(0.65)

        .effect()
        .file("modules/mba-premades/icons/misc/food3.webp")
        .atLocation(token, { offset: { x: -45, y: -61 } })
        .scaleToObject(0.4)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .duration(9000)
        .fadeIn(750)
        .fadeOut(750)
        .rotate(20)
        .delay(6000)
        .name(`${token.document.name} Create food and Water`)

        .effect()
        .file("animated-spell-effects-cartoon.cantrips.mending.yellow")
        .atLocation(token, { offset: { x: -70, y: 22 } })
        .scaleToObject(0.8)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .delay(6750)
        .playbackRate(0.65)

        .effect()
        .file("modules/mba-premades/icons/misc/food4.webp")
        .atLocation(token, { offset: { x: -70, y: 22 } })
        .scaleToObject(0.4)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .duration(8000)
        .fadeIn(750)
        .fadeOut(750)
        .rotate(20)
        .delay(7000)
        .name(`${token.document.name} Create food and Water`)

        .effect()
        .file("animated-spell-effects-cartoon.cantrips.mending.yellow")
        .atLocation(token, { offset: { x: 0, y: 75 } })
        .scaleToObject(0.8)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .delay(7750)
        .playbackRate(0.65)

        .effect()
        .file("modules/mba-premades/icons/misc/food5.webp")
        .atLocation(token, { offset: { x: 0, y: 75 } })
        .scaleToObject(0.45)
        .filter("Glow", { color: 0xd2d651 })
        .opacity(0.9)
        .duration(7000)
        .fadeIn(750)
        .fadeOut(750)
        .rotate(20)
        .delay(8000)
        .name(`${token.document.name} Create food and Water`)

        .effect()
        .file("jb2a.magic_signs.circle.02.conjuration.outro.dark_yellow")
        .atLocation(token)
        .scaleToObject(2)
        .belowTokens()
        .delay(8500)

        .play();
}