export async function augury({ speaker, actor, token, character, item, args, scope, workflow }) {
    let offset = [
        { x: 0, y: -0.55 },
        { x: -0.5, y: -0.15 },
        { x: -0.3, y: 0.45 },
        { x: 0.3, y: 0.45 },
        { x: 0.5, y: -0.15 }
    ];
    
    await new Sequence()

        .wait(750)

        .effect()
        .file("jb2a.icon.runes03.blue")
        .attachTo(workflow.token, { offset: offset[0], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .scaleIn(0, 250, { ease: "easeOutBack" })
        .fadeIn(300)
        .fadeOut(500)
        .zIndex(1)
        .duration(12000)
        .aboveLighting()

        .effect()
        .file("jb2a.impact.010.blue")
        .attachTo(workflow.token, { offset: offset[0], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .zIndex(1)
        .aboveLighting()

        .effect()
        .file("jb2a.icon.runes03.blue")
        .delay(1000)
        .attachTo(workflow.token, { offset: offset[1], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .scaleIn(0, 250, { ease: "easeOutBack" })
        .fadeIn(300)
        .fadeOut(500)
        .zIndex(1)
        .duration(11000)
        .aboveLighting()

        .effect()
        .file("jb2a.impact.010.blue")
        .delay(1000)
        .attachTo(workflow.token, { offset: offset[1], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .zIndex(1)
        .aboveLighting()

        .effect()
        .file("jb2a.icon.runes03.blue")
        .delay(2000)
        .attachTo(workflow.token, { offset: offset[2], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .scaleIn(0, 250, { ease: "easeOutBack" })
        .fadeIn(300)
        .fadeOut(500)
        .zIndex(1)
        .duration(10000)
        .aboveLighting()

        .effect()
        .file("jb2a.impact.010.blue")
        .delay(2000)
        .attachTo(workflow.token, { offset: offset[2], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .zIndex(1)
        .aboveLighting()

        .effect()
        .file("jb2a.icon.runes03.blue")
        .delay(3000)
        .attachTo(workflow.token, { offset: offset[3], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .scaleIn(0, 250, { ease: "easeOutBack" })
        .fadeIn(300)
        .fadeOut(500)
        .zIndex(1)
        .duration(9000)
        .aboveLighting()

        .effect()
        .file("jb2a.impact.010.blue")
        .delay(3000)
        .attachTo(workflow.token, { offset: offset[3], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .zIndex(1)
        .aboveLighting()

        .effect()
        .file("jb2a.icon.runes03.blue")
        .delay(4000)
        .attachTo(workflow.token, { offset: offset[4], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .scaleIn(0, 250, { ease: "easeOutBack" })
        .fadeIn(300)
        .fadeOut(500)
        .zIndex(1)
        .duration(8000)
        .aboveLighting()

        .effect()
        .file("jb2a.impact.010.blue")
        .delay(4000)
        .attachTo(workflow.token, { offset: offset[4], gridUnits: true, followRotation: false })
        .scaleToObject(0.5)
        .zIndex(1)
        .aboveLighting()

        .effect()
        .file("jb2a.particles.inward.blue.02.01")
        .delay(5000)
        .attachTo(workflow.token)
        .scaleToObject(2.7 * workflow.token.document.texture.scaleX)
        .belowTokens()
        .fadeIn(2000)
        .fadeOut(1000)
        .duration(7000)

        .effect()
        .file("jb2a.dodecahedron.rune.below.blueyellow")
        .delay(5000)
        .attachTo(workflow.token)
        .scaleToObject(2.7 * workflow.token.document.texture.scaleX)
        .belowTokens()
        .fadeIn(2000)
        .fadeOut(1000)
        .duration(7000)
        .filter("ColorMatrix", { hue: 160 })

        .play()
}