export async function shapeWater({ speaker, actor, token, character, item, args, scope, workflow }) {
    new Sequence()
    
        .wait(1000)

        .effect()
        .file("animated-spell-effects-cartoon.water.49")
        .attachTo(token, { offset: { x: 0.5, y: 0 }, gridUnits: true, followRotation: false })
        .scaleToObject(2)
        .fadeIn(250)
        .fadeOut(500)
        .scaleIn(0, 500, { ease: "easeOutCubic" })
        .rotate(0)
        .belowTokens()
        .opacity(1)

        .effect()
        .file("animated-spell-effects-cartoon.water.49")
        .attachTo(token, { offset: { x: -0, y: 0.5 }, gridUnits: true, followRotation: false })
        .scaleToObject(2)
        .fadeIn(250)
        .fadeOut(500)
        .scaleIn(0, 500, { ease: "easeOutCubic" })
        .rotate(-90)
        .belowTokens()
        .opacity(1)

        .effect()
        .file("animated-spell-effects-cartoon.water.49")
        .attachTo(token, { offset: { x: -0, y: -0.5 }, gridUnits: true, followRotation: false })
        .scaleToObject(2)
        .fadeIn(250)
        .fadeOut(500)
        .scaleIn(0, 500, { ease: "easeOutCubic" })
        .rotate(90)
        .belowTokens()
        .opacity(1)

        .effect()
        .file("animated-spell-effects-cartoon.water.49")
        .attachTo(token, { offset: { x: -0.5, y: -0 }, gridUnits: true, followRotation: false })
        .scaleToObject(2)
        .fadeIn(250)
        .scaleIn(0, 500, { ease: "easeOutCubic" })
        .rotate(180)
        .fadeOut(500)
        .belowTokens()
        .opacity(1)

        .effect()
        .file("animated-spell-effects-cartoon.water.63")
        .attachTo(token, { offset: { x: 0, y: 0 }, gridUnits: true, followRotation: false })
        .scaleToObject(2)
        .fadeOut(250)
        .belowTokens()

        .effect()
        .file("jb2a.wind_stream.200.white")
        .attachTo(token, { offset: { x: 0, y: 0 }, gridUnits: true, followRotation: false })
        .scaleToObject(2)
        .fadeIn(1000)
        .fadeOut(1000)
        .duration(7000)
        .playbackRate(0.5)
        .opacity(0.45)
        .filter("ColorMatrix", { saturate: 1, brightness: 2 })
        .rotate(90)
        .tint("#2db4e1")
        .mask()

        .effect()
        .file("animated-spell-effects-cartoon.water.69")
        .attachTo(token, { offset: { x: -0.23 * token.document.width, y: -0.05 }, gridUnits: true, followRotation: false })
        .scaleToObject(1.35, { considerTokenScale: true })
        .fadeIn(1000)
        .fadeOut(1000)
        .duration(7500)
        .filter("ColorMatrix", { saturate: -1, brightness: 0 })
        .filter("Blur", { blurX: 5, blurY: 10 })
        .opacity(0.3)

        .effect()
        .delay(700)
        .file("animated-spell-effects-cartoon.water.69")
        .attachTo(token, { offset: { x: 0.23 * token.document.width, y: -0.05 }, gridUnits: true, followRotation: false })
        .scaleToObject(1.35, { considerTokenScale: true })
        .fadeIn(1000)
        .fadeOut(1000)
        .duration(7500)
        .filter("ColorMatrix", { saturate: -1, brightness: 0 })
        .filter("Blur", { blurX: 5, blurY: 10 })
        .opacity(0.3)
        .mirrorX()

        .effect()
        .file("animated-spell-effects-cartoon.water.69")
        .attachTo(token, { offset: { x: -0.33 * token.document.width, y: -0.05 }, gridUnits: true, followRotation: false })
        .scaleToObject(1.35, { considerTokenScale: true })
        .fadeIn(1000)
        .fadeOut(1000)
        .duration(7500)
        .zIndex(0.1)

        .effect()
        .delay(700)
        .file("animated-spell-effects-cartoon.water.69")
        .attachTo(token, { offset: { x: 0.33 * token.document.width, y: -0.05 }, gridUnits: true, followRotation: false })
        .scaleToObject(1.35, { considerTokenScale: true })
        .fadeIn(1000)
        .fadeOut(1000)
        .duration(7500)
        .zIndex(0.1)
        .mirrorX()

        .play()
}